# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Kildin Sami spellchecker"
sjd = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Kildin Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
sjd = "TRANSLATE: A spellchecker for Kildin Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sjd"

[windows]
system_product_code = "{CEB34CB1-2CD9-4686-AD11-CD8264D5504A}_is1"
legacy_product_codes = [
    { value = "8438EAA8-D729-4B11-A794-8CAC68346802", kind = "nsis" },
    { value = "B620EA1F-7E32-48E0-99FF-350041A2E989", kind = "nsis" }
]
extra_locales = { sjd-RU = "sjd" }

[package.speller]
name = "Kildin Sami"
version = "0.1.1"

[package.grammar]
name = "Kildin Sami"
version = "0.1.0"

[package.tts-textproc]
name = "Kildin Sami"
version = "0.1.0"

[package.hyphenator]
name = "Kildin Sami"
version = "0.1.0"
