template = "https://github.com/giellalt/template-lang-und"
rev_id = 258
template_sha = "b5271fc37dc1cf0a7448e0553c24b3f857121d34"

[replacements]
__GLOTTOLOG_ID__ = "kild1236"
__REPO__ = "lang-sjd"
__UND2C__ = "sjd"
__UNDEFINED__ = "Kildin Sami"
__UND__ = "sjd"
